name: opc_data_filtering
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - beautifulsoup4=4.12.3
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - click=8.1.7
  - colorama=0.4.6
  - fasttext=0.9.2
  - jieba=0.42.1
  - joblib=1.4.2
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mecab=0.996
  - mecab-python3=1.0.8
  - ncurses=6.5
  - nltk=3.9.1
  - openssl=3.4.0
  - pandas=2.2.3
  - pip=24.3.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pygments=2.18.0
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytz=2024.1
  - readline=8.2
  - regex=2024.11.6
  - setuptools=75.6.0
  - six=1.17.0
  - soupsieve=2.5
  - tk=8.6.13
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unidic-lite=1.0.8
  - wheel=0.45.1
  - pip:
      - esprima==4.0.1
      - numpy==1.26.4
      - zhconv==1.4.3
