EXTENSION_TO_PROGRAM = {
    "c++": "cpp",
    "cc": "cpp",
    "cp": "cpp",
    "cpp": "cpp",
    "cxx": "cpp",
    "h++": "cpp",
    "hh": "cpp",
    "hpp": "cpp",
    "hxx": "cpp",
    "inl": "cpp",
    "ipp": "cpp",
    "tcc": "cpp",
    "tpp": "cpp",
    "C": "cpp",
    "H": "cpp",
    "cppm": "cpp",
    "ino": "cpp",
    "ixx": "cpp",
    "re": "cpp",
    "txx": "cpp",
    "cake": "csharp",
    "cs": "csharp",
    "cshtml": "csharp",
    "csx": "csharp",
    "pp": "csharp",
    "linq": "csharp",
    "c": "c",
    "h": "c",
    "cats": "c",
    "idc": "c",
    "w": "c",
    "go": "go",
    "xht": "html",
    "htm": "html",
    "html": "html",
    "xhtml": "html",
    "html.hl": "html",
    "hta": "html",
    "java": "java",
    "jav": "java",
    "jsh": "java",
    "es6": "javascript",
    "js": "javascript",
    "jsm": "javascript",
    "pac": "javascript",
    "sjs": "javascript",
    "xsjslib": "javascript",
    "_js": "javascript",
    "bones": "javascript",
    "jake": "javascript",
    "jsb": "javascript",
    "jscad": "javascript",
    "jsfl": "javascript",
    "jss": "javascript",
    "njs": "javascript",
    "ssjs": "javascript",
    "xsjs": "javascript",
    "cjs": "javascript",
    "javascript": "javascript",
    "jslib": "javascript",
    "jspre": "javascript",
    "jsx": "javascript",
    "mjs": "javascript",
    "bzl": "python",
    "gyp": "python",
    "py": "python",
    "pyde": "python",
    "pyw": "python",
    "lmi": "python",
    "pyp": "python",
    "pyt": "python",
    "tac": "python",
    "wsgi": "python",
    "xpy": "python",
    "gypi": "python",
    "py3": "python",
    "pyi": "python",
    "rpy": "python",
    "spec": "python",
    "json": "json",
    "geojson": "json",
    "lock": "json",
    "topojson": "json",
    "json5": "json",
    "jsonld": "json",
    "yaml": "yaml",
    "yml": "yaml",
    "reek": "yaml",
    "rviz": "yaml",
    "sublime-syntax": "yaml",
    "syntax": "yaml",
    "yaml-tmlanguage": "yaml",
    "bash": "shell",
    "bats": "shell",
    "command": "shell",
    "ksh": "shell",
    "sh": "shell",
    "tmux": "shell",
    "tool": "shell",
    "zsh": "shell",
    "sh.in": "shell",
    "sqf": "sqf",
    "hqf": "sqf",
    "cql": "sql",
    "db2": "sql",
    "ddl": "sql",
    "pkb": "sql",
    "pks": "sql",
    "plb": "sql",
    "plsql": "sql",
    "prc": "sql",
    "sql": "sql",
    "udf": "sql",
    "pls": "sql",
    "pck": "sql",
    "tab": "sql",
    "viw": "sql",
    "rsx": "r",
    "r": "r",
    "rd": "r",
    "hlean": "lean",
    "lean": "lean",
    "coq": "coq",
    "ctp": "php",
    "php": "php",
    "phpt": "php",
    "aw": "php",
    "php3": "php",
    "php4": "php",
    "php5": "php",
    "phps": "php",
    "builder": "ruby",
    "gemspec": "ruby",
    "jbuilder": "ruby",
    "podspec": "ruby",
    "rabl": "ruby",
    "rake": "ruby",
    "rb": "ruby",
    "rbw": "ruby",
    "ru": "ruby",
    "ruby": "ruby",
    "thor": "ruby",
    "god": "ruby",
    "irbrc": "ruby",
    "mspec": "ruby",
    "rbuild": "ruby",
    "rbx": "ruby",
    "watchr": "ruby",
    "eye": "ruby",
    "pluginspec": "ruby",
    "prawn": "ruby",
    "rbi": "ruby",
    "rs": "rust",
    "rs.in": "rust",
    "bsl": "1c enterprise",
    "os": "1c enterprise",
    "2da": "2-dimensional array",
    "4dm": "4d",
    "abap": "abap",
    "asddls": "abap cds",
    "abnf": "abnf",
    "asc": "ags script",
    "ash": "ags script",
    "aidl": "aidl",
    "al": "al",
    "ampl": "ampl",
    "mod": "ampl",
    "g4": "antlr",
    "apib": "api blueprint",
    "apl": "apl",
    "dyalog": "apl",
    "asl": "asl",
    "dsl": "asl",
    "asn": "asn.1",
    "asn1": "asn.1",
    "asax": "asp.net",
    "ascx": "asp.net",
    "ashx": "asp.net",
    "asmx": "asp.net",
    "aspx": "asp.net",
    "axd": "asp.net",
    "dats": "ats",
    "hats": "ats",
    "sats": "ats",
    "as": "actionscript",
    "adb": "ada",
    "ada": "ada",
    "ads": "ada",
    "txt": "text",
    "afm": "adobe font metrics",
    "agda": "agda",
    "als": "alloy",
    "OutJob": "altium designer",
    "PcbDoc": "altium designer",
    "PrjPCB": "altium designer",
    "SchDoc": "altium designer",
    "angelscript": "angelscript",
    "xml": "xml",
    "apacheconf": "apacheconf",
    "vhost": "apacheconf",
    "cls": "apex",
    "trigger": "apex",
    "agc": "apollo guidance computer",
    "applescript": "applescript",
    "scpt": "applescript",
    "arc": "arc",
    "asciidoc": "asciidoc",
    "adoc": "asciidoc",
    "aj": "aspectj",
    "asm": "assembly",
    "a51": "assembly",
    "i": "assembly",
    "inc": "assembly",
    "nas": "assembly",
    "nasm": "assembly",
    "astro": "astro",
    "asy": "asymptote",
    "aug": "augeas",
    "ahk": "autohotkey",
    "ahkl": "autohotkey",
    "au3": "autoit",
    "avdl": "avro idl",
    "awk": "awk",
    "auk": "awk",
    "gawk": "awk",
    "mawk": "awk",
    "nawk": "awk",
    "bas": "basic",
    "bqn": "bqn",
    "bal": "ballerina",
    "bat": "batchfile",
    "cmd": "batchfile",
    "bf": "beef",
    "befunge": "befunge",
    "be": "berry",
    "bib": "bibtex",
    "bibtex": "bibtex",
    "bicep": "bicep",
    "bicepparam": "bicep",
    "bs": "bikeshed",
    "bison": "bison",
    "bb": "bitbake",
    "bbappend": "bitbake",
    "bbclass": "bitbake",
    "blade": "blade",
    "decls": "blitzbasic",
    "bmx": "blitzmax",
    "bsv": "bluespec",
    "boo": "boo",
    "bpl": "boogie",
    "b": "brainfuck",
    "brs": "brightscript",
    "c-objdump": "c-objdump",
    "chs": "c2hs haskell",
    "cds": "cap cds",
    "cil": "cil",
    "clp": "clips",
    "cmake": "cmake",
    "in": "cmake",
    "cob": "cobol",
    "cbl": "cobol",
    "ccp": "cobol",
    "cobol": "cobol",
    "cpy": "cobol",
    "dae": "collada",
    "cson": "cson",
    "css": "css",
    "csv": "csv",
    "cue": "cue",
    "cabal": "cabal config",
    "caddyfile": "caddyfile",
    "cdc": "cadence",
    "cairo": "cairo",
    "mligo": "cameligo",
    "capnp": "cap'n proto",
    "mss": "cartocss",
    "ceylon": "ceylon",
    "chpl": "chapel",
    "ch": "charity",
    "crc32": "checksums",
    "md2": "checksums",
    "md4": "checksums",
    "md5": "checksums",
    "sha1": "checksums",
    "sha2": "checksums",
    "sha224": "checksums",
    "sha256": "checksums",
    "sha256sum": "checksums",
    "sha3": "checksums",
    "sha384": "checksums",
    "sha512": "checksums",
    "ck": "chuck",
    "circom": "circom",
    "cirru": "cirru",
    "clw": "clarion",
    "clar": "clarity",
    "asp": "classic asp",
    "icl": "clean",
    "dcl": "clean",
    "click": "click",
    "clj": "clojure",
    "boot": "clojure",
    "cl2": "clojure",
    "cljc": "clojure",
    "cljs": "clojure",
    "hl": "clojure",
    "cljscm": "clojure",
    "cljx": "clojure",
    "hic": "clojure",
    "soy": "closure templates",
    "conllu": "conll-u",
    "conll": "conll-u",
    "ql": "codeql",
    "qll": "codeql",
    "coffee": "coffeescript",
    "_coffee": "coffeescript",
    "cjsx": "coffeescript",
    "iced": "coffeescript",
    "cfm": "coldfusion",
    "cfml": "coldfusion",
    "cfc": "coldfusion cfc",
    "lisp": "common lisp",
    "asd": "common lisp",
    "cl": "common lisp",
    "l": "common lisp",
    "lsp": "common lisp",
    "ny": "common lisp",
    "podsl": "common lisp",
    "sexp": "common lisp",
    "cwl": "common workflow language",
    "cps": "component pascal",
    "v": "coq",
    "cppobjdump": "cpp-objdump",
    "c++-objdump": "cpp-objdump",
    "c++objdump": "cpp-objdump",
    "cpp-objdump": "cpp-objdump",
    "cxx-objdump": "cpp-objdump",
    "creole": "creole",
    "cr": "crystal",
    "orc": "csound",
    "udo": "csound",
    "csd": "csound document",
    "sco": "csound score",
    "cu": "cuda",
    "cuh": "cuda",
    "curry": "curry",
    "cy": "cycript",
    "cyp": "cypher",
    "cypher": "cypher",
    "pyx": "cython",
    "pxd": "cython",
    "pxi": "cython",
    "d": "d",
    "di": "d",
    "d-objdump": "d-objdump",
    "d2": "d2",
    "com": "digital command language",
    "dm": "dm",
    "zone": "dns zone",
    "arpa": "dns zone",
    "dfy": "dafny",
    "darcspatch": "darcs patch",
    "dpatch": "darcs patch",
    "dart": "dart",
    "dwl": "dataweave",
    "dsc": "debian package control file",
    "dhall": "dhall",
    "diff": "diff",
    "patch": "diff",
    "x": "directx 3d file",
    "dockerfile": "dockerfile",
    "djs": "dogescript",
    "env": "dotenv",
    "dylan": "dylan",
    "dyl": "dylan",
    "intr": "dylan",
    "lid": "dylan",
    "e": "e",
    "eml": "e-mail",
    "mbox": "e-mail",
    "ebnf": "ebnf",
    "ecl": "ecl",
    "eclxml": "ecl",
    "ejs": "ejs",
    "ect": "ejs",
    "t": "ejs",
    "jst": "ejs",
    "eq": "eq",
    "sch": "eagle",
    "brd": "eagle",
    "eb": "easybuild",
    "epj": "ecere projects",
    "edge": "edge",
    "edgeql": "edgeql",
    "esdl": "edgeql",
    "editorconfig": "editorconfig",
    "edc": "edje data collection",
    "ex": "elixir",
    "exs": "elixir",
    "elm": "elm",
    "elv": "elvish",
    "el": "emacs lisp",
    "emacs": "emacs lisp",
    "desktop": "emacs lisp",
    "em": "emberscript",
    "emberscript": "emberscript",
    "erl": "erlang",
    "app": "erlang",
    "src": "erlang",
    "es": "erlang",
    "escript": "erlang",
    "hrl": "erlang",
    "xrl": "erlang",
    "yrl": "erlang",
    "fs": "f#",
    "fsi": "f#",
    "fsx": "f#",
    "fst": "f*",
    "fsti": "f*",
    "flf": "figlet font",
    "fir": "firrtl",
    "fx": "flux",
    "flux": "flux",
    "factor": "factor",
    "fy": "fancy",
    "fancypack": "fancy",
    "fan": "fantom",
    "dsp": "faust",
    "fnl": "fennel",
    "f": "filebench wml",
    "ftl": "fluent",
    "for": "formatted",
    "fth": "forth",
    "4th": "forth",
    "forth": "forth",
    "fr": "forth",
    "frt": "forth",
    "f77": "fortran",
    "fpp": "fortran",
    "f90": "fortran free form",
    "f03": "fortran free form",
    "f08": "fortran free form",
    "f95": "fortran free form",
    "bi": "freebasic",
    "fut": "futhark",
    "g": "g-code",
    "cnc": "g-code",
    "gco": "g-code",
    "gcode": "g-code",
    "gaml": "gaml",
    "gms": "gams",
    "gap": "gap",
    "gd": "gap",
    "gi": "gap",
    "tst": "gap",
    "md": "markdown",
    "gdb": "gdb",
    "gdbinit": "gdb",
    "ged": "gedcom",
    "glsl": "glsl",
    "fp": "glsl",
    "frag": "glsl",
    "frg": "glsl",
    "fsh": "glsl",
    "fshader": "glsl",
    "geo": "glsl",
    "geom": "glsl",
    "glslf": "glsl",
    "glslv": "glsl",
    "gs": "glsl",
    "gshader": "glsl",
    "rchit": "glsl",
    "rmiss": "glsl",
    "shader": "glsl",
    "tesc": "glsl",
    "tese": "glsl",
    "vert": "glsl",
    "vrx": "glsl",
    "vs": "glsl",
    "vsh": "glsl",
    "vshader": "glsl",
    "gn": "gn",
    "gni": "gn",
    "gsc": "gsc",
    "csc": "gsc",
    "gsh": "gsc",
    "gml": "game maker language",
    "gmi": "gemini",
    "4gl": "genero 4gl",
    "per": "genero per",
    "kid": "genshi",
    "ebuild": "gentoo ebuild",
    "eclass": "gentoo eclass",
    "gbr": "gerber image",
    "cmp": "gerber image",
    "gbl": "gerber image",
    "gbo": "gerber image",
    "gbp": "gerber image",
    "gbs": "gerber image",
    "gko": "gerber image",
    "gpb": "gerber image",
    "gpt": "gerber image",
    "gtl": "gerber image",
    "gto": "gerber image",
    "gtp": "gerber image",
    "gts": "gerber image",
    "ncl": "gerber image",
    "sol": "gerber image",
    "po": "gettext catalog",
    "pot": "gettext catalog",
    "feature": "gherkin",
    "story": "gherkin",
    "gitconfig": "git config",
    "gleam": "gleam",
    "gjs": "glimmer js",
    "glf": "glyph",
    "bdf": "glyph bitmap distribution format",
    "gp": "gnuplot",
    "gnu": "gnuplot",
    "gnuplot": "gnuplot",
    "p": "gnuplot",
    "plot": "gnuplot",
    "plt": "gnuplot",
    "gdnlib": "godot resource",
    "gdns": "godot resource",
    "tres": "godot resource",
    "tscn": "godot resource",
    "golo": "golo",
    "gst": "gosu",
    "gsx": "gosu",
    "vark": "gosu",
    "grace": "grace",
    "gradle": "gradle",
    "kts": "gradle kotlin dsl",
    "gf": "grammatical framework",
    "graphql": "graphql",
    "gql": "graphql",
    "graphqls": "graphql",
    "dot": "graphviz (dot)",
    "gv": "graphviz (dot)",
    "groovy": "groovy",
    "grt": "groovy",
    "gtpl": "groovy",
    "gvy": "groovy",
    "gsp": "groovy server pages",
    "cfg": "haproxy",
    "hcl": "hcl",
    "nomad": "hcl",
    "tf": "hcl",
    "tfvars": "hcl",
    "workflow": "hcl",
    "hlsl": "hlsl",
    "cginc": "hlsl",
    "fxh": "hlsl",
    "hlsli": "hlsl",
    "hocon": "hocon",
    "ecr": "html+ecr",
    "eex": "html+eex",
    "heex": "html+eex",
    "leex": "html+eex",
    "erb": "html+erb",
    "deface": "html+erb",
    "rhtml": "html+erb",
    "phtml": "html+php",
    "razor": "html+razor",
    "http": "http",
    "hxml": "hxml",
    "hack": "hack",
    "hhi": "hack",
    "haml": "haml",
    "handlebars": "handlebars",
    "hbs": "handlebars",
    "hb": "harbour",
    "hs": "haskell",
    "hs-boot": "haskell",
    "hsc": "haskell",
    "hx": "haxe",
    "hxsl": "haxe",
    "q": "hiveql",
    "hql": "hiveql",
    "hc": "holyc",
    "hy": "hy",
    "pro": "idl",
    "dlm": "idl",
    "ipf": "igor pro",
    "ini": "ini",
    "cnf": "ini",
    "dof": "ini",
    "lektorproject": "ini",
    "prefs": "ini",
    "properties": "ini",
    "url": "ini",
    "irclog": "irc log",
    "weechatlog": "irc log",
    "idr": "idris",
    "lidr": "idris",
    "gitignore": "ignore list",
    "ijm": "imagej macro",
    "imba": "imba",
    "ni": "inform 7",
    "i7x": "inform 7",
    "ink": "ink",
    "iss": "inno setup",
    "isl": "inno setup",
    "io": "io",
    "ik": "ioke",
    "thy": "isabelle",
    "ijs": "j",
    "jcl": "jcl",
    "flex": "jflex",
    "jflex": "jflex",
    "4DForm": "json",
    "4DProject": "json",
    "avsc": "json",
    "gltf": "json",
    "har": "json",
    "ice": "json",
    "JSON-tmLanguage": "json",
    "jsonl": "json",
    "mcmeta": "json",
    "sarif": "json",
    "tfstate": "json",
    "backup": "json",
    "webapp": "json",
    "webmanifest": "json",
    "yy": "json",
    "yyp": "json",
    "jsonc": "json with comments",
    "code-snippets": "json with comments",
    "code-workspace": "json with comments",
    "sublime-build": "json with comments",
    "sublime-color-scheme": "json with comments",
    "sublime-commands": "json with comments",
    "sublime-completions": "json with comments",
    "sublime-keymap": "json with comments",
    "sublime-macro": "json with comments",
    "sublime-menu": "json with comments",
    "sublime-mousemap": "json with comments",
    "sublime-project": "json with comments",
    "sublime-settings": "json with comments",
    "sublime-theme": "json with comments",
    "sublime-workspace": "json with comments",
    "sublime_metrics": "json with comments",
    "sublime_session": "json with comments",
    "jq": "jsoniq",
    "janet": "janet",
    "j": "jasmin",
    "jsp": "java server pages",
    "tag": "java server pages",
    "snap": "jest snapshot",
    "mps": "jetbrains mps",
    "mpl": "jetbrains mps",
    "msd": "jetbrains mps",
    "jinja": "jinja",
    "j2": "jinja",
    "jinja2": "jinja",
    "jison": "jison",
    "jisonlex": "jison lex",
    "ol": "jolie",
    "iol": "jolie",
    "jsonnet": "jsonnet",
    "libsonnet": "jsonnet",
    "jl": "julia",
    "ipynb": "jupyter notebook",
    "just": "just",
    "krl": "krl",
    "ksy": "kaitai struct",
    "kak": "kakounescript",
    "ks": "kerboscript",
    "kicad_pcb": "kicad layout",
    "kicad_mod": "kicad layout",
    "kicad_wks": "kicad layout",
    "kicad_sch": "kicad schematic",
    "kit": "kit",
    "kt": "kotlin",
    "ktm": "kotlin",
    "csl": "kusto",
    "kql": "kusto",
    "lfe": "lfe",
    "ll": "llvm",
    "lol": "lolcode",
    "lsl": "lsl",
    "lslp": "lsl",
    "lvproj": "labview",
    "lvclass": "labview",
    "lvlib": "labview",
    "lark": "lark",
    "lasso": "lasso",
    "las": "lasso",
    "lasso8": "lasso",
    "lasso9": "lasso",
    "latte": "latte",
    "less": "less",
    "lex": "lex",
    "ligo": "ligolang",
    "ly": "lilypond",
    "ily": "lilypond",
    "m": "limbo",
    "ld": "linker script",
    "lds": "linker script",
    "liquid": "liquid",
    "lagda": "literate agda",
    "litcoffee": "literate coffeescript",
    "lhs": "literate haskell",
    "ls": "livescript",
    "_ls": "livescript",
    "xm": "logos",
    "xi": "logos",
    "lgt": "logtalk",
    "logtalk": "logtalk",
    "lkml": "lookml",
    "lookml": "lookml",
    "lua": "lua",
    "fcgi": "lua",
    "nse": "lua",
    "p8": "lua",
    "pd_lua": "lua",
    "rbxs": "lua",
    "rockspec": "lua",
    "wlua": "lua",
    "luau": "luau",
    "mumps": "m",
    "m4": "m4",
    "mc": "m4",
    "matlab": "matlab",
    "ms": "maxscript",
    "mcr": "maxscript",
    "mdx": "mdx",
    "mlir": "mlir",
    "mq4": "mql4",
    "mqh": "mql4",
    "mq5": "mql5",
    "mtml": "mtml",
    "muf": "muf",
    "m2": "macaulay2",
    "mak": "makefile",
    "make": "makefile",
    "makefile": "makefile",
    "mk": "makefile",
    "mkfile": "makefile",
    "mako": "mako",
    "mao": "mako",
    "livemd": "markdown",
    "markdown": "markdown",
    "mdown": "markdown",
    "mdwn": "markdown",
    "mkd": "markdown",
    "mkdn": "markdown",
    "mkdown": "markdown",
    "ronn": "markdown",
    "scd": "markdown",
    "workbook": "markdown",
    "marko": "marko",
    "mask": "mask",
    "mathematica": "mathematica",
    "cdf": "mathematica",
    "ma": "mathematica",
    "mt": "mathematica",
    "nb": "mathematica",
    "nbp": "mathematica",
    "wl": "mathematica",
    "wlt": "mathematica",
    "maxpat": "max",
    "maxhelp": "max",
    "maxproj": "max",
    "mxt": "max",
    "pat": "max",
    "moo": "mercury",
    "mmd": "mermaid",
    "mermaid": "mermaid",
    "metal": "metal",
    "sln": "microsoft visual studio solution",
    "minid": "minid",
    "mint": "mint",
    "druby": "mirah",
    "duby": "mirah",
    "mirah": "mirah",
    "mo": "modelica",
    "i3": "modula-3",
    "ig": "modula-3",
    "m3": "modula-3",
    "mg": "modula-3",
    "mms": "module management system",
    "mmk": "module management system",
    "mojo": "mojo",
    "monkey": "monkey",
    "monkey2": "monkey",
    "moon": "moonscript",
    "s": "motorola 68k assembly",
    "x68": "motorola 68k assembly",
    "move": "move",
    "muse": "muse",
    "mustache": "mustache",
    "myt": "myghty",
    "nasl": "nasl",
    "neon": "neon",
    "nl": "nl",
    "nsi": "nsis",
    "nsh": "nsis",
    "nss": "nwscript",
    "ne": "nearley",
    "nearley": "nearley",
    "n": "nemerle",
    "axs": "netlinx",
    "axi": "netlinx",
    "nlogo": "netlogo",
    "nf": "nextflow",
    "nginx": "nginx",
    "nginxconf": "nginx",
    "nim": "nim",
    "nimble": "nim",
    "nimrod": "nim",
    "nims": "nim",
    "ninja": "ninja",
    "nit": "nit",
    "nix": "nix",
    "nu": "nu",
    "numpy": "numpy",
    "numpyw": "numpy",
    "numsc": "numpy",
    "njk": "nunjucks",
    "ml": "ocaml",
    "eliom": "ocaml",
    "eliomi": "ocaml",
    "ml4": "ocaml",
    "mli": "ocaml",
    "mll": "ocaml",
    "mly": "ocaml",
    "ob2": "oberon",
    "objdump": "objdump",
    "odin": "object data instance notation",
    "mm": "objective-c++",
    "sj": "objective-j",
    "omgrofl": "omgrofl",
    "opa": "opa",
    "opal": "opal",
    "rego": "open policy agent",
    "opencl": "opencl",
    "qasm": "openqasm",
    "scad": "openscad",
    "plist": "openstep property list",
    "glyphs": "openstep property list",
    "fea": "opentype feature file",
    "org": "org",
    "ox": "ox",
    "oxh": "ox",
    "oxo": "ox",
    "oxygene": "oxygene",
    "oz": "oz",
    "p4": "p4",
    "pddl": "pddl",
    "pegjs": "peg.js",
    "bdy": "plsql",
    "fnc": "plsql",
    "spc": "plsql",
    "tpb": "plsql",
    "tps": "plsql",
    "trg": "plsql",
    "vw": "plsql",
    "pgsql": "plpgsql",
    "pov": "pov-ray sdl",
    "pact": "pact",
    "pan": "pan",
    "psc": "papyrus",
    "parrot": "parrot",
    "pasm": "parrot assembly",
    "pir": "parrot internal representation",
    "pas": "pascal",
    "dfm": "pascal",
    "dpr": "pascal",
    "lpr": "pascal",
    "pascal": "pascal",
    "pwn": "pawn",
    "sma": "pawn",
    "pep": "pep8",
    "pl": "perl",
    "cgi": "perl",
    "perl": "perl",
    "ph": "perl",
    "plx": "perl",
    "pm": "perl",
    "psgi": "perl",
    "pic": "pic",
    "chem": "pic",
    "pkl": "pickle",
    "pig": "piglatin",
    "pike": "pike",
    "pmod": "pike",
    "puml": "plantuml",
    "iuml": "plantuml",
    "plantuml": "plantuml",
    "pod": "pod",
    "pod6": "pod 6",
    "pogo": "pogoscript",
    "polar": "polar",
    "pony": "pony",
    "por": "portugol",
    "pcss": "postcss",
    "postcss": "postcss",
    "ps": "postscript",
    "eps": "postscript",
    "epsi": "postscript",
    "pfa": "postscript",
    "pbt": "powerbuilder",
    "sra": "powerbuilder",
    "sru": "powerbuilder",
    "srw": "powerbuilder",
    "ps1": "powershell",
    "psd1": "powershell",
    "psm1": "powershell",
    "praat": "praat",
    "prisma": "prisma",
    "pde": "processing",
    "prolog": "prolog",
    "yap": "prolog",
    "pml": "promela",
    "spin": "propeller spin",
    "proto": "protocol buffer",
    "textproto": "protocol buffer text format",
    "pbtxt": "protocol buffer text format",
    "p9": "prover9",
    "pub": "public key",
    "jade": "pug",
    "pug": "pug",
    "pd": "pure data",
    "pb": "purebasic",
    "pbi": "purebasic",
    "purs": "purescript",
    "arr": "pyret",
    "pytb": "python traceback",
    "qs": "q#",
    "qml": "qml",
    "qbs": "qml",
    "pri": "qmake",
    "raml": "raml",
    "rbs": "rbs",
    "rdoc": "rdoc",
    "rbbas": "realbasic",
    "rbfrm": "realbasic",
    "rbmnu": "realbasic",
    "rbres": "realbasic",
    "rbtbar": "realbasic",
    "rbuistate": "realbasic",
    "rexx": "rexx",
    "pprx": "rexx",
    "rex": "rexx",
    "qmd": "rmarkdown",
    "rmd": "rmarkdown",
    "ron": "ron",
    "rpgle": "rpgle",
    "sqlrpgle": "rpgle",
    "rnh": "runoff",
    "rno": "runoff",
    "rkt": "racket",
    "rktd": "racket",
    "rktl": "racket",
    "scrbl": "racket",
    "rl": "ragel",
    "6pl": "raku",
    "6pm": "raku",
    "nqp": "raku",
    "p6": "raku",
    "p6l": "raku",
    "p6m": "raku",
    "pl6": "raku",
    "pm6": "raku",
    "raku": "raku",
    "rakumod": "raku",
    "rsc": "rascal",
    "raw": "raw token data",
    "res": "rescript",
    "rei": "reason",
    "religo": "reasonligo",
    "reb": "rebol",
    "r2": "rebol",
    "r3": "rebol",
    "rebol": "rebol",
    "red": "red",
    "reds": "red",
    "cw": "redcode",
    "regexp": "regular expression",
    "regex": "regular expression",
    "rsh": "renderscript",
    "rtf": "rich text format",
    "ring": "ring",
    "riot": "riot",
    "robot": "robotframework",
    "roc": "roc",
    "roff": "roff",
    "1": "roff",
    "1in": "roff",
    "1m": "roff",
    "1x": "roff",
    "2": "roff",
    "3": "roff",
    "3in": "roff",
    "3m": "roff",
    "3p": "roff",
    "3pm": "roff",
    "3qt": "roff",
    "3x": "roff",
    "4": "roff",
    "5": "roff",
    "6": "roff",
    "7": "roff",
    "8": "roff",
    "9": "roff",
    "man": "roff",
    "mdoc": "roff",
    "me": "roff",
    "nr": "roff",
    "tmac": "roff",
    "rg": "rouge",
    "sas": "sas",
    "scss": "scss",
    "te": "selinux policy",
    "smt2": "smt",
    "smt": "smt",
    "sparql": "sparql",
    "rq": "sparql",
    "mysql": "sql",
    "srt": "srecode template",
    "star": "star",
    "stl": "stl",
    "ston": "ston",
    "svg": "svg",
    "sage": "sage",
    "sagews": "sage",
    "sls": "saltstack",
    "sass": "sass",
    "scala": "scala",
    "kojo": "scala",
    "sbt": "scala",
    "sc": "scala",
    "scaml": "scaml",
    "scenic": "scenic",
    "scm": "scheme",
    "sld": "scheme",
    "sps": "scheme",
    "ss": "scheme",
    "sci": "scilab",
    "sce": "scilab",
    "self": "self",
    "zsh-theme": "shell",
    "sh-session": "shellsession",
    "shen": "shen",
    "sieve": "sieve",
    "sfv": "simple file verification",
    "sl": "slash",
    "slim": "slim",
    "slint": "slint",
    "cocci": "smpl",
    "smali": "smali",
    "st": "smalltalk",
    "tpl": "smarty",
    "smithy": "smithy",
    "smk": "snakemake",
    "snakefile": "snakemake",
    "sp": "sourcepawn",
    "sfd": "spline font database",
    "nut": "squirrel",
    "stan": "stan",
    "fun": "standard ml",
    "sig": "standard ml",
    "sml": "standard ml",
    "do": "stata",
    "ado": "stata",
    "doh": "stata",
    "ihlp": "stata",
    "mata": "stata",
    "matah": "stata",
    "sthlp": "stata",
    "styl": "stylus",
    "sss": "sugarss",
    "svelte": "svelte",
    "sw": "sway",
    "rnw": "sweave",
    "swift": "swift",
    "sv": "systemverilog",
    "svh": "systemverilog",
    "vh": "systemverilog",
    "8xp": "ti program",
    "tlv": "tl-verilog",
    "tla": "tla",
    "toml": "toml",
    "tsv": "tsv",
    "tsx": "tsx",
    "txl": "txl",
    "talon": "talon",
    "tcl": "tcl",
    "adp": "tcl",
    "sdc": "tcl",
    "tm": "tcl",
    "xdc": "tcl",
    "tcsh": "tcsh",
    "csh": "tcsh",
    "tex": "tex",
    "aux": "tex",
    "bbx": "tex",
    "cbx": "tex",
    "dtx": "tex",
    "ins": "tex",
    "lbx": "tex",
    "ltx": "tex",
    "mkii": "tex",
    "mkiv": "tex",
    "mkvi": "tex",
    "sty": "tex",
    "toc": "tex",
    "tea": "tea",
    "tftpl": "terraform template",
    "texinfo": "texinfo",
    "texi": "texinfo",
    "txi": "texinfo",
    "no": "text",
    "TextGrid": "textgrid",
    "textile": "textile",
    "thrift": "thrift",
    "toit": "toit",
    "tu": "turing",
    "ttl": "turtle",
    "twig": "twig",
    "tl": "type language",
    "ts": "typescript",
    "cts": "typescript",
    "mts": "typescript",
    "typ": "typst",
    "upc": "unified parallel c",
    "anim": "unity3d asset",
    "asset": "unity3d asset",
    "mat": "unity3d asset",
    "meta": "unity3d asset",
    "prefab": "unity3d asset",
    "unity": "unity3d asset",
    "uno": "uno",
    "uc": "unrealscript",
    "ur": "urweb",
    "urs": "urweb",
    "frm": "vba",
    "vba": "vba",
    "vbs": "vbscript",
    "vcl": "vcl",
    "vhdl": "vhdl",
    "vhd": "vhdl",
    "vhf": "vhdl",
    "vhi": "vhdl",
    "vho": "vhdl",
    "vhs": "vhdl",
    "vht": "vhdl",
    "vhw": "vhdl",
    "vala": "vala",
    "vapi": "vala",
    "vdf": "valve data format",
    "vtl": "velocity template language",
    "veo": "verilog",
    "vim": "vim script",
    "vimrc": "vim script",
    "vmb": "vim script",
    "snip": "vim snippet",
    "snippet": "vim snippet",
    "snippets": "vim snippet",
    "vb": "visual basic .net",
    "vbhtml": "visual basic .net",
    "ctl": "visual basic 6.0",
    "Dsr": "visual basic 6.0",
    "volt": "volt",
    "vue": "vue",
    "vy": "vyper",
    "wdl": "wdl",
    "wgsl": "wgsl",
    "mtl": "wavefront material",
    "obj": "wavefront object",
    "owl": "web ontology language",
    "wast": "webassembly",
    "wat": "webassembly",
    "wit": "webassembly interface type",
    "webidl": "webidl",
    "vtt": "webvtt",
    "whiley": "whiley",
    "mediawiki": "wikitext",
    "wiki": "wikitext",
    "wikitext": "wikitext",
    "reg": "windows registry entries",
    "ws": "witcher script",
    "wlk": "wollok",
    "wren": "wren",
    "xbm": "x bitmap",
    "xpm": "x pixmap",
    "x10": "x10",
    "xc": "xc",
    "adml": "xml",
    "admx": "xml",
    "ant": "xml",
    "axaml": "xml",
    "axml": "xml",
    "builds": "xml",
    "ccproj": "xml",
    "ccxml": "xml",
    "clixml": "xml",
    "cproject": "xml",
    "cscfg": "xml",
    "csdef": "xml",
    "csproj": "xml",
    "ct": "xml",
    "depproj": "xml",
    "dita": "xml",
    "ditamap": "xml",
    "ditaval": "xml",
    "config": "xml",
    "dotsettings": "xml",
    "filters": "xml",
    "fsproj": "xml",
    "fxml": "xml",
    "glade": "xml",
    "gmx": "xml",
    "grxml": "xml",
    "hzp": "xml",
    "iml": "xml",
    "ivy": "xml",
    "jelly": "xml",
    "jsproj": "xml",
    "kml": "xml",
    "launch": "xml",
    "mdpolicy": "xml",
    "mjml": "xml",
    "mxml": "xml",
    "natvis": "xml",
    "ndproj": "xml",
    "nproj": "xml",
    "nuspec": "xml",
    "odd": "xml",
    "osm": "xml",
    "pkgproj": "xml",
    "proj": "xml",
    "props": "xml",
    "ps1xml": "xml",
    "psc1": "xml",
    "pt": "xml",
    "qhelp": "xml",
    "rdf": "xml",
    "resx": "xml",
    "rss": "xml",
    "scxml": "xml",
    "sfproj": "xml",
    "shproj": "xml",
    "srdf": "xml",
    "storyboard": "xml",
    "sublime-snippet": "xml",
    "targets": "xml",
    "tml": "xml",
    "ui": "xml",
    "urdf": "xml",
    "ux": "xml",
    "vbproj": "xml",
    "vcxproj": "xml",
    "vsixmanifest": "xml",
    "vssettings": "xml",
    "vstemplate": "xml",
    "vxml": "xml",
    "wixproj": "xml",
    "wsdl": "xml",
    "wsf": "xml",
    "wxi": "xml",
    "wxl": "xml",
    "wxs": "xml",
    "x3d": "xml",
    "xacro": "xml",
    "xaml": "xml",
    "xib": "xml",
    "xlf": "xml",
    "xliff": "xml",
    "xmi": "xml",
    "dist": "xml",
    "xmp": "xml",
    "xproj": "xml",
    "xsd": "xml",
    "xspec": "xml",
    "xul": "xml",
    "zcml": "xml",
    "stTheme": "xml property list",
    "tmCommand": "xml property list",
    "tmLanguage": "xml property list",
    "tmPreferences": "xml property list",
    "tmSnippet": "xml property list",
    "tmTheme": "xml property list",
    "xsp-config": "xpages",
    "metadata": "xpages",
    "xpl": "xproc",
    "xproc": "xproc",
    "xquery": "xquery",
    "xq": "xquery",
    "xql": "xquery",
    "xqm": "xquery",
    "xqy": "xquery",
    "xs": "xs",
    "xslt": "xslt",
    "xsl": "xslt",
    "xojo_code": "xojo",
    "xojo_menu": "xojo",
    "xojo_report": "xojo",
    "xojo_script": "xojo",
    "xojo_toolbar": "xojo",
    "xojo_window": "xojo",
    "xsh": "xonsh",
    "xtend": "xtend",
    "mir": "yaml",
    "sed": "yaml",
    "yang": "yang",
    "yar": "yara",
    "yara": "yara",
    "yasnippet": "yasnippet",
    "y": "yacc",
    "yacc": "yacc",
    "yul": "yul",
    "zap": "zap",
    "xzap": "zap",
    "zil": "zil",
    "mud": "zil",
    "zeek": "zeek",
    "bro": "zeek",
    "zs": "zenscript",
    "zep": "zephir",
    "zig": "zig",
    "zon": "zig",
    "zimpl": "zimpl",
    "zmpl": "zimpl",
    "zpl": "zimpl",
    "service": "desktop",
    "dircolors": "dircolors",
    "ec": "ec",
    "eh": "ec",
    "edn": "edn",
    "fish": "fish",
    "hoon": "hoon",
    "kv": "kvlang",
    "mrc": "mirc script",
    "mcfunction": "mcfunction",
    "mu": "mupad",
    "nanorc": "nanorc",
    "nc": "nesc",
    "ooc": "ooc",
    "rst": "restructuredtext",
    "rest": "restructuredtext",
    "templ": "templ",
    "wisp": "wisp",
    "prg": "xbase",
    "prw": "xbase"
}