FILENAME_TO_PROGRAM = {
    "APKBUILD": "alpine abuild",
    "ant.xml": "ant build system",
    "build.xml": "ant build system",
    ".htaccess": "apacheconf",
    "apache2.conf": "apacheconf",
    "httpd.conf": "apacheconf",
    ".browserslistrc": "browserslist",
    "browserslist": "browserslist",
    "CMakeLists.txt": "cmake",
    "CODEOWNERS": "codeowners",
    "cabal.config": "cabal config",
    "cabal.project": "cabal config",
    "Caddyfile": "caddyfile",
    "MD5SUMS": "checksums",
    "SHA1SUMS": "checksums",
    "SHA256SUMS": "checksums",
    "SHA256SUMS.txt": "checksums",
    "SHA512SUMS": "checksums",
    "checksums.txt": "checksums",
    "cksums": "checksums",
    "md5sum.txt": "checksums",
    "riemann.config": "clojure",
    "firestore.rules": "cloud firestore security rules",
    "Cakefile": "coffeescript",
    "Containerfile": "dockerfile",
    "Dockerfile": "dockerfile",
    ".env": "dotenv",
    ".env.ci": "dotenv",
    ".env.dev": "dotenv",
    ".env.development": "dotenv",
    ".env.development.local": "dotenv",
    ".env.example": "dotenv",
    ".env.local": "dotenv",
    ".env.prod": "dotenv",
    ".env.production": "dotenv",
    ".env.sample": "dotenv",
    ".env.staging": "dotenv",
    ".env.test": "dotenv",
    ".env.testing": "dotenv",
    "Earthfile": "earthly",
    ".editorconfig": "editorconfig",
    "mix.lock": "elixir",
    ".abbrev_defs": "emacs lisp",
    ".emacs": "emacs lisp",
    ".emacs.desktop": "emacs lisp",
    ".gnus": "emacs lisp",
    ".spacemacs": "emacs lisp",
    ".viper": "emacs lisp",
    "Cask": "emacs lisp",
    "Project.ede": "emacs lisp",
    "_emacs": "emacs lisp",
    "abbrev_defs": "emacs lisp",
    "Emakefile": "erlang",
    "rebar.config": "erlang",
    "rebar.config.lock": "erlang",
    "rebar.lock": "erlang",
    ".factor-boot-rc": "factor",
    ".factor-rc": "factor",
    "Fakefile": "fancy",
    ".gn": "gn",
    "Gemfile.lock": "gemfile.lock",
    ".gitattributes": "git attributes",
    ".gitconfig": "git config",
    ".gitmodules": "git config",
    ".git-blame-ignore-revs": "git revision list",
    "go.sum": "go checksums",
    "go.work.sum": "go checksums",
    "go.mod": "go module",
    "go.work": "go workspace",
    "project.godot": "godot resource",
    "Jenkinsfile": "groovy",
    "haproxy.cfg": "haproxy",
    ".scalafix.conf": "hocon",
    ".scalafmt.conf": "hocon",
    "HOSTS": "ini",
    "hosts": "ini",
    ".coveragerc": "ini",
    ".flake8": "ini",
    ".pylintrc": "ini",
    "buildozer.spec": "ini",
    "pylintrc": "ini",
    "vlcrc": "ini",
    ".atomignore": "ignore list",
    ".babelignore": "ignore list",
    ".bzrignore": "ignore list",
    ".coffeelintignore": "ignore list",
    ".cvsignore": "ignore list",
    ".dockerignore": "ignore list",
    ".eleventyignore": "ignore list",
    ".eslintignore": "ignore list",
    ".gitignore": "ignore list",
    ".markdownlintignore": "ignore list",
    ".nodemonignore": "ignore list",
    ".npmignore": "ignore list",
    ".prettierignore": "ignore list",
    ".stylelintignore": "ignore list",
    ".vercelignore": "ignore list",
    ".vscodeignore": "ignore list",
    "gitignore-global": "ignore list",
    "gitignore_global": "ignore list",
    "ROOT": "isabelle root",
    "MANIFEST.MF": "jar manifest",
    ".all-contributorsrc": "json",
    ".arcconfig": "json",
    ".auto-changelog": "json",
    ".c8rc": "json",
    ".htmlhintrc": "json",
    ".imgbotconfig": "json",
    ".nycrc": "json",
    ".tern-config": "json",
    ".tern-project": "json",
    ".watchmanconfig": "json",
    "MODULE.bazel.lock": "json",
    "Pipfile.lock": "json",
    "composer.lock": "json",
    "deno.lock": "json",
    "flake.lock": "json",
    "mcmod.info": "json",
    ".babelrc": "json",
    ".devcontainer.json": "json",
    ".eslintrc.json": "json",
    ".jscsrc": "json",
    ".jshintrc": "json",
    ".jslintrc": "json",
    ".swcrc": "json",
    "api-extractor.json": "json",
    "devcontainer.json": "json",
    "jsconfig.json": "json",
    "language-configuration.json": "json",
    "tsconfig.json": "json",
    "tslint.json": "json",
    "Jakefile": "javascript",
    "Notebook": "jupyter notebook",
    ".JUSTFILE": "just",
    ".Justfile": "just",
    ".justfile": "just",
    "JUSTFILE": "just",
    "Justfile": "just",
    "justfile": "just",
    "kakrc": "kakounescript",
    "fp-lib-table": "kicad layout",
    "Lexer.x": "lex",
    "lexer.x": "lex",
    "ld.script": "linker script",
    "Slakefile": "livescript",
    ".luacheckrc": "lua",
    "configure.ac": "m4sugar",
    "BSDmakefile": "makefile",
    "GNUmakefile": "makefile",
    "Kbuild": "makefile",
    "Makefile": "makefile",
    "Makefile.am": "makefile",
    "Makefile.boot": "makefile",
    "Makefile.frag": "makefile",
    "Makefile.in": "makefile",
    "Makefile.inc": "makefile",
    "Makefile.wat": "makefile",
    "makefile": "makefile",
    "makefile.sco": "makefile",
    "mkfile": "makefile",
    "contents.lr": "markdown",
    "pom.xml": "maven pom",
    "meson.build": "meson",
    "meson_options.txt": "meson",
    "descrip.mmk": "module management system",
    "descrip.mms": "module management system",
    ".npmrc": "npm config",
    "nextflow.config": "nextflow",
    "nginx.conf": "nginx",
    "nim.cfg": "nim",
    "Nukefile": "nu",
    ".ackrc": "option list",
    ".rspec": "option list",
    ".yardopts": "option list",
    "ackrc": "option list",
    "mocha.opts": "option list",
    ".php": "php",
    ".php_cs": "php",
    ".php_cs.dist": "php",
    "Phakefile": "php",
    ".latexmkrc": "perl",
    "Makefile.PL": "perl",
    "Rexfile": "perl",
    "ack": "perl",
    "cpanfile": "perl",
    "latexmkrc": "perl",
    "requirements-dev.txt": "text",
    "requirements.txt": "text",
    "Procfile": "procfile",
    "Modulefile": "puppet",
    ".gclient": "python",
    "DEPS": "python",
    "SConscript": "python",
    "SConstruct": "python",
    "wscript": "python",
    "installscript.qs": "qt script",
    "toolchain_installscript.qs": "qt script",
    "m3makefile": "quake",
    "m3overrides": "quake",
    ".Rprofile": "r",
    "expr-dist": "r",
    ".inputrc": "readline config",
    "inputrc": "readline config",
    "language-subtag-registry.txt": "record jar",
    "_redirects": "redirect rules",
    "eqnrc": "roff",
    "mmn": "roff",
    "mmt": "roff",
    "troffrc": "roff",
    "troffrc-end": "roff",
    ".irbrc": "ruby",
    ".pryrc": "ruby",
    ".simplecov": "ruby",
    "Appraisals": "ruby",
    "Berksfile": "ruby",
    "Brewfile": "ruby",
    "Buildfile": "ruby",
    "Capfile": "ruby",
    "Dangerfile": "ruby",
    "Deliverfile": "ruby",
    "Fastfile": "ruby",
    "Gemfile": "ruby",
    "Guardfile": "ruby",
    "Jarfile": "ruby",
    "Mavenfile": "ruby",
    "Podfile": "ruby",
    "Puppetfile": "ruby",
    "Rakefile": "ruby",
    "Snapfile": "ruby",
    "Steepfile": "ruby",
    "Thorfile": "ruby",
    "Vagrantfile": "ruby",
    "buildfile": "ruby",
    "file_contexts": "selinux policy",
    "genfs_contexts": "selinux policy",
    "initial_sids": "selinux policy",
    "port_contexts": "selinux policy",
    "security_classes": "selinux policy",
    "ssh-config": "ssh config",
    "ssh_config": "ssh config",
    "sshconfig": "ssh config",
    "sshconfig.snip": "ssh config",
    "sshd-config": "ssh config",
    "sshd_config": "ssh config",
    ".bash_aliases": "shell",
    ".bash_functions": "shell",
    ".bash_history": "shell",
    ".bash_logout": "shell",
    ".bash_profile": "shell",
    ".bashrc": "shell",
    ".cshrc": "shell",
    ".envrc": "shell",
    ".flaskenv": "shell",
    ".kshrc": "shell",
    ".login": "shell",
    ".profile": "shell",
    ".tmux.conf": "shell",
    ".zlogin": "shell",
    ".zlogout": "shell",
    ".zprofile": "shell",
    ".zshenv": "shell",
    ".zshrc": "shell",
    "9fs": "shell",
    "PKGBUILD": "shell",
    "bash_aliases": "shell",
    "bash_logout": "shell",
    "bash_profile": "shell",
    "bashrc": "shell",
    "cshrc": "shell",
    "gradlew": "shell",
    "kshrc": "shell",
    "login": "shell",
    "man": "shell",
    "profile": "shell",
    "tmux.conf": "shell",
    "zlogin": "shell",
    "zlogout": "shell",
    "zprofile": "shell",
    "zshenv": "shell",
    "zshrc": "shell",
    ".shellcheckrc": "shellcheck config",
    "Singularity": "singularity",
    "Snakefile": "snakemake",
    "Android.bp": "soong",
    "BUCK": "starlark",
    "BUILD": "starlark",
    "BUILD.bazel": "starlark",
    "MODULE.bazel": "starlark",
    "Tiltfile": "starlark",
    "WORKSPACE": "starlark",
    "WORKSPACE.bazel": "starlark",
    "Cargo.lock": "toml",
    "Cargo.toml.orig": "toml",
    "Gopkg.lock": "toml",
    "Pipfile": "toml",
    "pdm.lock": "toml",
    "poetry.lock": "toml",
    "owh": "tcl",
    "starfield": "tcl",
    "CITATION": "text",
    "CITATIONS": "text",
    "COPYING": "text",
    "COPYING.regex": "text",
    "COPYRIGHT.regex": "text",
    "FONTLOG": "text",
    "INSTALL": "text",
    "INSTALL.mysql": "text",
    "LICENSE": "text",
    "LICENSE.mysql": "text",
    "NEWS": "text",
    "README.me": "text",
    "README.mysql": "text",
    "README.nss": "text",
    "click.me": "text",
    "delete.me": "text",
    "keep.me": "text",
    "package.mask": "text",
    "package.use.mask": "text",
    "package.use.stable.mask": "text",
    "read.me": "text",
    "readme.1st": "text",
    "test.me": "text",
    "use.mask": "text",
    "use.stable.mask": "text",
    ".tm_properties": "textmate properties",
    ".exrc": "vim script",
    ".gvimrc": "vim script",
    ".nvimrc": "vim script",
    ".vimrc": "vim script",
    "_vimrc": "vim script",
    "gvimrc": "vim script",
    "nvimrc": "vim script",
    "vimrc": "vim script",
    ".wgetrc": "wget config",
    "encodings.dir": "x font directory index",
    "fonts.alias": "x font directory index",
    "fonts.dir": "x font directory index",
    "fonts.scale": "x font directory index",
    ".XCompose": "xcompose",
    "XCompose": "xcompose",
    "xcompose": "xcompose",
    ".classpath": "xml",
    ".cproject": "xml",
    ".project": "xml",
    "App.config": "xml",
    "NuGet.config": "xml",
    "Settings.StyleCop": "xml",
    "Web.Debug.config": "xml",
    "Web.Release.config": "xml",
    "Web.config": "xml",
    "packages.config": "xml",
    ".clang-format": "yaml",
    ".clang-tidy": "yaml",
    ".gemrc": "yaml",
    "CITATION.cff": "yaml",
    "glide.lock": "yaml",
    "yarn.lock": "yaml",
    ".curlrc": "curl config",
    "_curlrc": "curl config",
    "crontab": "crontab",
    ".dir_colors": "dircolors",
    ".dircolors": "dircolors",
    "DIR_COLORS": "dircolors",
    "_dir_colors": "dircolors",
    "_dircolors": "dircolors",
    "dir_colors": "dircolors",
    ".nanorc": "nanorc",
    "nanorc": "nanorc",
    "robots.txt": "robots.txt"
}