PROGRAM_TO_TYPE = {
    "1c enterprise": "code",
    "2-dimensional array": "data",
    "4d": "code",
    "abap": "code",
    "abap cds": "code",
    "abnf": "data",
    "ags script": "code",
    "aidl": "code",
    "al": "code",
    "ampl": "code",
    "antlr": "code",
    "api blueprint": "code",
    "apl": "code",
    "asl": "code",
    "asn.1": "data",
    "asp.net": "code",
    "ats": "code",
    "actionscript": "code",
    "ada": "code",
    "adblock filter list": "data",
    "adobe font metrics": "data",
    "agda": "code",
    "alloy": "code",
    "alpine abuild": "code",
    "altium designer": "data",
    "angelscript": "code",
    "ant build system": "data",
    "antlers": "code",
    "apacheconf": "data",
    "apex": "code",
    "apollo guidance computer": "code",
    "applescript": "code",
    "arc": "code",
    "asciidoc": "text",
    "aspectj": "code",
    "assembly": "code",
    "astro": "code",
    "asymptote": "code",
    "augeas": "code",
    "autohotkey": "code",
    "autoit": "code",
    "avro idl": "data",
    "awk": "code",
    "basic": "code",
    "bqn": "code",
    "ballerina": "code",
    "batchfile": "code",
    "beef": "code",
    "befunge": "code",
    "berry": "code",
    "bibtex": "data",
    "bicep": "code",
    "bikeshed": "code",
    "bison": "code",
    "bitbake": "code",
    "blade": "code",
    "blitzbasic": "code",
    "blitzmax": "code",
    "bluespec": "code",
    "bluespec bh": "code",
    "boo": "code",
    "boogie": "code",
    "brainfuck": "code",
    "brighterscript": "code",
    "brightscript": "code",
    "browserslist": "data",
    "c": "code",
    "csharp": "code",
    "cpp": "code",
    "c-objdump": "data",
    "c2hs haskell": "code",
    "cap cds": "code",
    "cil": "data",
    "clips": "code",
    "cmake": "code",
    "cobol": "code",
    "codeowners": "data",
    "collada": "data",
    "cson": "data",
    "css": "data",
    "csv": "data",
    "cue": "code",
    "cweb": "code",
    "cabal config": "data",
    "caddyfile": "data",
    "cadence": "code",
    "cairo": "code",
    "cameligo": "code",
    "cap'n proto": "code",
    "cartocss": "data",
    "ceylon": "code",
    "chapel": "code",
    "charity": "code",
    "checksums": "data",
    "chuck": "code",
    "circom": "code",
    "cirru": "code",
    "clarion": "code",
    "clarity": "code",
    "classic asp": "code",
    "clean": "code",
    "click": "code",
    "clojure": "code",
    "closure templates": "code",
    "cloud firestore security rules": "data",
    "conll-u": "data",
    "codeql": "code",
    "coffeescript": "code",
    "coldfusion": "code",
    "coldfusion cfc": "code",
    "common lisp": "code",
    "common workflow language": "code",
    "component pascal": "code",
    "cool": "code",
    "coq": "code",
    "cpp-objdump": "data",
    "creole": "text",
    "crystal": "code",
    "csound": "code",
    "csound document": "code",
    "csound score": "code",
    "cuda": "code",
    "cue sheet": "data",
    "curry": "code",
    "cycript": "code",
    "cypher": "code",
    "cython": "code",
    "d": "code",
    "d-objdump": "data",
    "d2": "code",
    "digital command language": "code",
    "dm": "code",
    "dns zone": "data",
    "dtrace": "code",
    "dafny": "code",
    "darcs patch": "data",
    "dart": "code",
    "dataweave": "code",
    "debian package control file": "data",
    "denizenscript": "code",
    "dhall": "code",
    "diff": "code",
    "directx 3d file": "data",
    "dockerfile": "code",
    "dogescript": "code",
    "dotenv": "data",
    "dylan": "code",
    "e": "code",
    "e-mail": "data",
    "ebnf": "data",
    "ecl": "code",
    "eclipse": "code",
    "ejs": "code",
    "eq": "code",
    "eagle": "data",
    "earthly": "code",
    "easybuild": "data",
    "ecere projects": "data",
    "ecmarkup": "code",
    "edge": "code",
    "edgeql": "code",
    "editorconfig": "data",
    "edje data collection": "data",
    "eiffel": "code",
    "elixir": "code",
    "elm": "code",
    "elvish": "code",
    "elvish transcript": "code",
    "emacs lisp": "code",
    "emberscript": "code",
    "erlang": "code",
    "euphoria": "code",
    "f#": "code",
    "f*": "code",
    "figlet font": "data",
    "firrtl": "code",
    "flux": "code",
    "factor": "code",
    "fancy": "code",
    "fantom": "code",
    "faust": "code",
    "fennel": "code",
    "filebench wml": "code",
    "filterscript": "code",
    "fluent": "code",
    "formatted": "data",
    "forth": "code",
    "fortran": "code",
    "fortran free form": "code",
    "freebasic": "code",
    "freemarker": "code",
    "frege": "code",
    "futhark": "code",
    "g-code": "code",
    "gaml": "code",
    "gams": "code",
    "gap": "code",
    "gcc machine description": "code",
    "gdb": "code",
    "gdscript": "code",
    "gedcom": "data",
    "glsl": "code",
    "gn": "data",
    "gsc": "code",
    "game maker language": "code",
    "gemfile.lock": "data",
    "gemini": "text",
    "genero 4gl": "code",
    "genero per": "code",
    "genie": "code",
    "genshi": "code",
    "gentoo ebuild": "code",
    "gentoo eclass": "code",
    "gerber image": "data",
    "gettext catalog": "text",
    "gherkin": "code",
    "git attributes": "data",
    "git config": "data",
    "git revision list": "data",
    "gleam": "code",
    "glimmer js": "code",
    "glimmer ts": "code",
    "glyph": "code",
    "glyph bitmap distribution format": "data",
    "gnuplot": "code",
    "go": "code",
    "go checksums": "data",
    "go module": "data",
    "go workspace": "data",
    "godot resource": "data",
    "golo": "code",
    "gosu": "code",
    "grace": "code",
    "gradle": "data",
    "gradle kotlin dsl": "data",
    "grammatical framework": "code",
    "graph modeling language": "data",
    "graphql": "data",
    "graphviz (dot)": "data",
    "groovy": "code",
    "groovy server pages": "code",
    "haproxy": "data",
    "hcl": "code",
    "hlsl": "code",
    "hocon": "data",
    "html": "code",
    "html+ecr": "code",
    "html+eex": "code",
    "html+erb": "code",
    "html+php": "code",
    "html+razor": "code",
    "http": "data",
    "hxml": "data",
    "hack": "code",
    "haml": "code",
    "handlebars": "code",
    "harbour": "code",
    "haskell": "code",
    "haxe": "code",
    "hiveql": "code",
    "holyc": "code",
    "hosts file": "data",
    "hy": "code",
    "hyphy": "code",
    "idl": "code",
    "igor pro": "code",
    "ini": "data",
    "irc log": "data",
    "idris": "code",
    "ignore list": "data",
    "imagej macro": "code",
    "imba": "code",
    "inform 7": "code",
    "ink": "code",
    "inno setup": "code",
    "io": "code",
    "ioke": "code",
    "isabelle": "code",
    "isabelle root": "code",
    "j": "code",
    "jar manifest": "data",
    "jcl": "code",
    "jflex": "code",
    "json": "data",
    "json with comments": "data",
    "json5": "data",
    "jsonld": "data",
    "jsoniq": "code",
    "janet": "code",
    "jasmin": "code",
    "java": "code",
    "java properties": "data",
    "java server pages": "code",
    "javascript": "code",
    "javascript+erb": "code",
    "jest snapshot": "data",
    "jetbrains mps": "code",
    "jinja": "code",
    "jison": "code",
    "jison lex": "code",
    "jolie": "code",
    "jsonnet": "code",
    "julia": "code",
    "julia repl": "code",
    "jupyter notebook": "code",
    "just": "code",
    "krl": "code",
    "kaitai struct": "code",
    "kakounescript": "code",
    "kerboscript": "code",
    "kicad layout": "data",
    "kicad legacy layout": "data",
    "kicad schematic": "data",
    "kickstart": "data",
    "kit": "code",
    "kotlin": "code",
    "kusto": "data",
    "lfe": "code",
    "llvm": "code",
    "lolcode": "code",
    "lsl": "code",
    "ltspice symbol": "data",
    "labview": "code",
    "lark": "data",
    "lasso": "code",
    "latte": "code",
    "lean": "code",
    "lean 4": "code",
    "less": "code",
    "lex": "code",
    "ligolang": "code",
    "lilypond": "code",
    "limbo": "code",
    "linker script": "data",
    "linux kernel module": "data",
    "liquid": "code",
    "literate agda": "code",
    "literate coffeescript": "code",
    "literate haskell": "code",
    "livescript": "code",
    "logos": "code",
    "logtalk": "code",
    "lookml": "code",
    "loomscript": "code",
    "lua": "code",
    "luau": "code",
    "m": "code",
    "m4": "code",
    "m4sugar": "code",
    "matlab": "code",
    "maxscript": "code",
    "mdx": "text",
    "mlir": "code",
    "mql4": "code",
    "mql5": "code",
    "mtml": "code",
    "muf": "code",
    "macaulay2": "code",
    "makefile": "code",
    "mako": "code",
    "markdown": "text",
    "marko": "code",
    "mask": "code",
    "mathematica": "code",
    "maven pom": "data",
    "max": "code",
    "mercury": "code",
    "mermaid": "code",
    "meson": "code",
    "metal": "code",
    "microsoft developer studio project": "data",
    "microsoft visual studio solution": "data",
    "minid": "code",
    "miniyaml": "data",
    "mint": "code",
    "mirah": "code",
    "modelica": "code",
    "modula-2": "code",
    "modula-3": "code",
    "module management system": "code",
    "mojo": "code",
    "monkey": "code",
    "monkey c": "code",
    "moocode": "code",
    "moonscript": "code",
    "motoko": "code",
    "motorola 68k assembly": "code",
    "move": "code",
    "muse": "text",
    "mustache": "code",
    "myghty": "code",
    "nasl": "code",
    "ncl": "code",
    "neon": "data",
    "nl": "data",
    "nmodl": "code",
    "npm config": "data",
    "nsis": "code",
    "nwscript": "code",
    "nasal": "code",
    "nearley": "code",
    "nemerle": "code",
    "netlinx": "code",
    "netlinx+erb": "code",
    "netlogo": "code",
    "newlisp": "code",
    "nextflow": "code",
    "nginx": "data",
    "nim": "code",
    "ninja": "data",
    "nit": "code",
    "nix": "code",
    "nu": "code",
    "numpy": "code",
    "nunjucks": "code",
    "nushell": "code",
    "oasv2-json": "data",
    "oasv2-yaml": "data",
    "oasv3-json": "data",
    "oasv3-yaml": "data",
    "ocaml": "code",
    "oberon": "code",
    "objdump": "data",
    "object data instance notation": "data",
    "objectscript": "code",
    "objective-c": "code",
    "objective-c++": "code",
    "objective-j": "code",
    "odin": "code",
    "omgrofl": "code",
    "opa": "code",
    "opal": "code",
    "open policy agent": "code",
    "openapi specification v2": "data",
    "openapi specification v3": "data",
    "opencl": "code",
    "openedge abl": "code",
    "openqasm": "code",
    "openrc runscript": "code",
    "openscad": "code",
    "openstep property list": "data",
    "opentype feature file": "data",
    "option list": "data",
    "org": "text",
    "ox": "code",
    "oxygene": "code",
    "oz": "code",
    "p4": "code",
    "pddl": "code",
    "peg.js": "code",
    "php": "code",
    "plsql": "code",
    "plpgsql": "code",
    "pov-ray sdl": "code",
    "pact": "code",
    "pan": "code",
    "papyrus": "code",
    "parrot": "code",
    "parrot assembly": "code",
    "parrot internal representation": "code",
    "pascal": "code",
    "pawn": "code",
    "pep8": "code",
    "perl": "code",
    "pic": "code",
    "pickle": "data",
    "picolisp": "code",
    "piglatin": "code",
    "pike": "code",
    "pip requirements": "data",
    "pkl": "code",
    "plantuml": "data",
    "pod": "text",
    "pod 6": "text",
    "pogoscript": "code",
    "polar": "code",
    "pony": "code",
    "portugol": "code",
    "postcss": "data",
    "postscript": "code",
    "powerbuilder": "code",
    "powershell": "code",
    "praat": "code",
    "prisma": "data",
    "processing": "code",
    "procfile": "code",
    "proguard": "data",
    "prolog": "code",
    "promela": "code",
    "propeller spin": "code",
    "protocol buffer": "data",
    "protocol buffer text format": "data",
    "prover9": "code",
    "public key": "data",
    "pug": "code",
    "puppet": "code",
    "pure data": "data",
    "purebasic": "code",
    "purescript": "code",
    "pyret": "code",
    "python": "code",
    "python console": "code",
    "python traceback": "data",
    "q#": "code",
    "qml": "code",
    "qmake": "code",
    "qt script": "code",
    "quake": "code",
    "r": "code",
    "raml": "code",
    "rbs": "data",
    "rdoc": "text",
    "realbasic": "code",
    "rexx": "code",
    "rmarkdown": "text",
    "ron": "data",
    "rpc": "code",
    "rpgle": "code",
    "rpm spec": "data",
    "runoff": "code",
    "racket": "code",
    "ragel": "code",
    "raku": "code",
    "rascal": "code",
    "raw token data": "data",
    "rescript": "code",
    "readline config": "data",
    "reason": "code",
    "reasonligo": "code",
    "rebol": "code",
    "record jar": "data",
    "red": "code",
    "redcode": "code",
    "redirect rules": "data",
    "regular expression": "data",
    "ren'py": "code",
    "renderscript": "code",
    "rez": "code",
    "rich text format": "text",
    "ring": "code",
    "riot": "code",
    "robotframework": "code",
    "roc": "code",
    "roff": "text",
    "roff manpage": "code",
    "rouge": "code",
    "routeros script": "code",
    "ruby": "code",
    "rust": "code",
    "sas": "code",
    "scss": "data",
    "selinux policy": "data",
    "smt": "code",
    "sparql": "data",
    "sqf": "code",
    "sql": "code",
    "sqlpl": "code",
    "srecode template": "text",
    "ssh config": "data",
    "star": "data",
    "stl": "data",
    "ston": "data",
    "svg": "data",
    "swig": "code",
    "sage": "code",
    "saltstack": "code",
    "sass": "code",
    "scala": "code",
    "scaml": "code",
    "scenic": "code",
    "scheme": "code",
    "scilab": "code",
    "self": "code",
    "shaderlab": "code",
    "shell": "code",
    "shellcheck config": "data",
    "shellsession": "code",
    "shen": "code",
    "sieve": "code",
    "simple file verification": "data",
    "singularity": "code",
    "slash": "code",
    "slice": "code",
    "slim": "code",
    "slint": "code",
    "smpl": "code",
    "smali": "code",
    "smalltalk": "code",
    "smarty": "code",
    "smithy": "code",
    "snakemake": "code",
    "solidity": "code",
    "soong": "data",
    "sourcepawn": "code",
    "spline font database": "data",
    "squirrel": "code",
    "stan": "code",
    "standard ml": "code",
    "starlark": "code",
    "stata": "code",
    "stringtemplate": "code",
    "stylus": "code",
    "subrip text": "data",
    "sugarss": "code",
    "supercollider": "code",
    "svelte": "code",
    "sway": "code",
    "sweave": "text",
    "swift": "code",
    "systemverilog": "code",
    "ti program": "code",
    "tl-verilog": "code",
    "tla": "code",
    "toml": "data",
    "tsql": "code",
    "tsv": "data",
    "tsx": "code",
    "txl": "code",
    "talon": "code",
    "tcl": "code",
    "tcsh": "code",
    "tex": "text",
    "tea": "code",
    "terra": "code",
    "terraform template": "code",
    "texinfo": "text",
    "text": "text",
    "textgrid": "data",
    "textmate properties": "data",
    "textile": "text",
    "thrift": "code",
    "toit": "code",
    "turing": "code",
    "turtle": "data",
    "twig": "code",
    "type language": "data",
    "typescript": "code",
    "typst": "code",
    "unified parallel c": "code",
    "unity3d asset": "data",
    "unix assembly": "code",
    "uno": "code",
    "unrealscript": "code",
    "urweb": "code",
    "v": "code",
    "vba": "code",
    "vbscript": "code",
    "vcl": "code",
    "vhdl": "code",
    "vala": "code",
    "valve data format": "data",
    "velocity template language": "code",
    "verilog": "code",
    "vim help file": "text",
    "vim script": "code",
    "vim snippet": "code",
    "visual basic .net": "code",
    "visual basic 6.0": "code",
    "volt": "code",
    "vue": "code",
    "vyper": "code",
    "wdl": "code",
    "wgsl": "code",
    "wavefront material": "data",
    "wavefront object": "data",
    "web ontology language": "data",
    "webassembly": "code",
    "webassembly interface type": "data",
    "webidl": "code",
    "webvtt": "data",
    "wget config": "data",
    "whiley": "code",
    "wikitext": "text",
    "win32 message file": "data",
    "windows registry entries": "data",
    "witcher script": "code",
    "wollok": "code",
    "world of warcraft addon data": "data",
    "wren": "code",
    "x bitmap": "data",
    "x font directory index": "data",
    "x pixmap": "data",
    "x10": "code",
    "xc": "code",
    "xcompose": "data",
    "xml": "data",
    "xml property list": "data",
    "xpages": "data",
    "xproc": "code",
    "xquery": "code",
    "xs": "code",
    "xslt": "code",
    "xojo": "code",
    "xonsh": "code",
    "xtend": "code",
    "yaml": "data",
    "yang": "data",
    "yara": "code",
    "yasnippet": "code",
    "yacc": "code",
    "yul": "code",
    "zap": "code",
    "zil": "code",
    "zeek": "code",
    "zenscript": "code",
    "zephir": "code",
    "zig": "code",
    "zimpl": "code",
    "curl config": "data",
    "crontab": "data",
    "desktop": "data",
    "dircolors": "data",
    "ec": "code",
    "edn": "data",
    "fish": "code",
    "hoon": "code",
    "jq": "code",
    "kvlang": "code",
    "mirc script": "code",
    "mcfunction": "code",
    "mupad": "code",
    "nanorc": "data",
    "nesc": "code",
    "ooc": "code",
    "q": "code",
    "restructuredtext": "text",
    "robots.txt": "data",
    "sed": "code",
    "templ": "code",
    "wisp": "code",
    "xbase": "code"
}